### ISSUE TITLE
建议对仓库的名称进行调整

### ISSUE THREAD

**Issue by Jzow** [Charity-Software-Organization/cso-portal-front-end#1]
cso-portal-front-end

可改为：

CSO-Portal-Front-End

**Comment by ghost** [comment]
Vue、Nuxt初始化项目时，不允许出现大写字母，我将仔细考察大写字母对该项目对影响程度，在进行修改

**Comment by Jzow** [comment]
@DongQinglin  如果不允许的话，那也没有关系

**Comment by Jzow** [comment]
我在进行观察的同时发现项目名称就依据小写，为了保持一致我把后台的仓库也改成小写
